project:
  type: website
  output-dir: docs
website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - machinelearning.qmd

format:
  html:
    page-layout: full
    theme: pulse
    css: styles.css
    toc: true



